# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contactNo', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
