# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
